version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: willyNilly12
      MYSQL_DATABASE: lms
      MYSQL_USER: admin
      MYSQL_PASSWORD: willyNilly12
    ports:
      - "3306:3306"